name: recsys
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch>=2.2.0
  - pytorch-cuda=12.1
  - faiss-gpu>=1.8
  - pip>=24
  - pip:
      - -r requirements-dev.txt
